version: '3.4'

services:
  postgres:    
    image: ******
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: *******
      POSTGRES_USER: *******
      POSTGRES_DB: ********
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
