# Generated by Django 4.1.7 on 2023-02-26 16:03

import AuthSys.authapp.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(max_length=25, validators=[AuthSys.authapp.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=25, validators=[AuthSys.authapp.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
